In [11]:
import time  # For handling time-related functions
import re  # For regular expressions
import numpy as np  # For numerical operations
import pandas as pd  # For data manipulation and analysis
from bs4 import BeautifulSoup  # For web scraping
from selenium import webdriver  # For browser automation
from selenium.webdriver.chrome.service import Service  # For configuring the ChromeDriver service

In [ ]:
# def get_driver():
#     """
#     Creates and configures a Chrome WebDriver instance for web scraping.

#     Returns:
#         WebDriver: Configured instance of the Chrome WebDriver.
#     """
#     # Set the path to the ChromeDriver executable
#     service = Service('D:/chromedriver-win64/chromedriver.exe')

#     # Configure Chrome options
#     options = webdriver.ChromeOptions()
    
#     # Ignore certificate errors
#     options.add_argument('--ignore-certificate-errors')
    
#     # Start the browser in maximized mode
#     options.add_argument('--start-maximized')

#     # Create a Chrome WebDriver instance with the specified service and options
#     driver = webdriver.Chrome(service=service, options=options)

#     # Return the WebDriver instance
#     return driver

In [24]:


def get_driver():
    options = webdriver.ChromeOptions()

    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--start-maximized')

    driver = webdriver.Chrome(options=options)
    return driver

In [67]:
# def get_page_source(url, delay=10):
#     """
#     Retrieves the page source of a specified URL using Selenium and BeautifulSoup.

#     Args:
#         url (str): The URL to scrape.
#         delay (int, optional): Delay in seconds to wait for the page to load. Default is 10 seconds.

#     Returns:
#         BeautifulSoup: The BeautifulSoup object representing the page source.
#     """
#     # Get a Chrome WebDriver instance
#     driver = get_driver()

#     # Open the specified URL in the browser
#     driver.get(url)

#     # Allow time for the page to load (adjust delay as needed)
#     time.sleep(delay)

#     # Get the page source using BeautifulSoup for parsing
#     page_source = BeautifulSoup(driver.page_source, 'html.parser')

#     # Close the WebDriver to release resources
#     driver.quit()

#     # Return the parsed page source
#     return page_source

In [44]:
def get_titles(page_source, first_page=False):
    """
    Extracts titles of problems from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.
        first_page (bool, optional): Flag indicating whether it's the first page. Default is False.

    Returns:
        list: List of extracted titles.
    """
    # Determine the starting index based on whether it's the first page or not
    start_index = 1 if first_page else 0

    # Find all title elements using BeautifulSoup
    title_elements = page_source.find_all(
        'a',
        class_=[
            'h-5 hover:text-blue-s dark:hover:text-dark-blue-s',
            'h-5 hover:text-blue-s dark:hover:text-dark-blue-s opacity-60'
        ]
    )[start_index:]

    # Extract text from title elements and store in a list
    titles = [title_element.text for title_element in title_elements]

    # Return the list of titles
    return titles

In [117]:
def get_title(page_source):
    """
    Extracts the title from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.

    Returns:
        str: The extracted title text.
    """
    # Find the title element using BeautifulSoup
    title_element = page_source.find(
        'a',
        class_=['mr-2 text-label-1 dark:text-dark-label-1 hover:text-label-1 dark:hover:text-dark-label-1 text-lg font-medium'
                

]
    )

    # Extract the text content from the title element
    title = title_element.text

    # Return the title
    return title

In [33]:
def get_problem_description(page_source):
    """
    Extracts the problem description from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.

    Returns:
        str: The extracted problem description text.
    """
    # Find the div element containing the problem description using BeautifulSoup
    description_element = page_source.find(
        'div',
        class_='xFUwe'
    )

    # Extract the text content from the description element
    description_text = description_element.text

    # Return the problem description
    return description_text

In [45]:
def get_problems_URL(page_source, first_page=False):
    """
    Extracts URLs of problems from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.
        first_page (bool, optional): Flag indicating whether it's the first page. Default is False.

    Returns:
        list: List of extracted problem URLs.
    """
    # Determine the starting index based on whether it's the first page or not
    start_index = 1 if first_page else 0

    # Find all problem elements with an 'a' tag and an 'href' attribute using BeautifulSoup
    problem_elements = page_source.find_all('a', href=True, class_=[
        'h-5 hover:text-blue-s dark:hover:text-dark-blue-s',
        'h-5 hover:text-blue-s dark:hover:text-dark-blue-s opacity-60'
    ])[start_index:]

    # Extract the 'href' attribute values from the problem elements and store in a list
    problems_url = [el['href'] for el in problem_elements]

    # Return the list of problem URLs
    return problems_url

In [146]:

def get_topic_tags(page_source):
    """
    Extracts the topic tags from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.

    Returns:
        str: Comma-separated string of extracted topic tags.
    """
    # Initialize an empty list to store topic tags
    # topic_tags = []

    # Find all elements with the specified class using BeautifulSoup
    # topic_tag_elements = page_source.find_all('a',
    #              class_='mr-4 rounded-xl px-2 py-1 text-xs transition-colors text-label-2 dark:text-dark-label-2 hover:text-label-2 dark:hover:text-dark-label-2 bg-fill-3 dark:bg-dark-fill-3 hover:bg-fill-2 dark:hover:bg-dark-fill-2') 
    # topic_tag_elements = page_source.find_all('a', class_=['no-underline hover:text-current relative inline-flex items-center justify-center text-caption px-2 py-1 gap-1 rounded-full bg-fill-secondary text-text-secondary',
    # #             'relative inline-flex gap-1 items-center justify-center bg-fill-secondary text-text-secondary text-caption px-2 py-1 gap-1  rounded-full bg-fill-secondary text-text-secondary'])
    # a_tags = page_source.find_all(
    #     'a',
    #     class_='no-underline hover:text-current relative inline-flex items-center justify-center text-caption px-2 py-1 gap-1 rounded-full bg-fill-secondary text-text-secondary'
    # )

    # div_tags = page_source.find_all(
    #     'div',
    #     class_='relative inline-flex gap-1 items-center justify-center bg-fill-secondary text-text-secondary text-caption px-2 py-1 gap-1 rounded-full bg-fill-secondary text-text-secondary'
    # )

    # topic_tag_elements = a_tags + div_tags
def get_topic_tags(page_source):

    container = page_source.find(
        'div',
        class_='mt-2 flex flex-wrap gap-1 pl-7'
    )

    topic_tag_elements = []

    # Preferred approach: use parent container
    if container is not None:
        topic_tag_elements = [
            elem.get_text(strip=True)
            for elem in container.find_all(['a', 'div'], recursive=False)
        ]

    # Fallback approach
    if not topic_tag_elements:

        # Find all matching anchor tags
        a_tags = page_source.find_all(
            'a',
            class_='no-underline hover:text-current relative inline-flex items-center justify-center text-caption px-2 py-1 gap-1 rounded-full bg-fill-secondary text-text-secondary'
        )

        # Find all matching div tags
        div_tags = page_source.find_all(
            'div',
            class_=lambda c: c and 'rounded-full' in c and 'text-caption' in c
        )

        topic_tag_elements = [
            elem.get_text(strip=True)
            for elem in (a_tags + div_tags)
        ]

    # Nothing found
    if not topic_tag_elements:
        return ''

    return ', '.join(f"'{tag}'" for tag in topic_tag_elements)

In [34]:
def get_likes(page_source):
    """
    Extracts the number of likes from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.

    Returns:
        str: The extracted number of likes.
    """
    # Find the element with the specified class using BeautifulSoup
    likes_element = page_source.find_all('div', class_='text-lg text-gray-6 dark:text-dark-gray-6')[0]

    # Find the next sibling element and extract the text content
    likes_count = likes_element.find_next_sibling().text

    # Return the extracted number of likes
    return likes_count

In [46]:
def get_dislikes(page_source):
    """
    Extracts the number of dislikes from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.

    Returns:
        str: The extracted number of dislikes.
    """
    # Find the element with the specified class using BeautifulSoup
    dislikes_element = page_source.find_all('div', class_='text-lg text-gray-6 dark:text-dark-gray-6')[1]

    # Find the next sibling element and extract the text content
    dislikes_count = dislikes_element.find_next_sibling().text

    # Return the extracted number of dislikes
    return dislikes_count

In [36]:
def get_similar_questions(page_source):
    """
    Extracts a list of similar questions from the given page source.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.

    Returns:
        str: Comma-separated string of extracted similar questions.
    """
    # Initialize an empty list to store similar questions
    similar_questions = []

    # Find all elements with the specified class using BeautifulSoup
    similar_question_elements = page_source.find_all('a', class_='text-sm font-medium transition-none text-label-1 dark:text-dark-label-1 hover:text-blue-s dark:hover:text-dark-blue-s')

    # Extract text content from each similar question element and append to the list
    for similar_question_element in similar_question_elements:
        similar_question = similar_question_element.text
        similar_questions.append(similar_question)

    # Join the list of similar questions into a comma-separated string
    similar_questions_str = ', '.join(f"'{item}'" for item in similar_questions)

    # Return the formatted string of similar questions
    return similar_questions_str

In [47]:
def get_single_page_df(url, first_page=False):
    """
    Creates a Pandas DataFrame for a single page of problems.

    Args:
        url (str): The URL of the page to scrape.
        first_page (bool, optional): Flag indicating whether it's the first page. Default is False.

    Returns:
        DataFrame: Pandas DataFrame containing titles, problem URLs, acceptances, and difficulties.
    """
    # Get the page source for the specified URL
    page_source = get_page_source(url)

    # Extract titles, problem URLs, acceptances, and difficulties from the page source
    titles = get_titles(page_source, first_page)
    problems_url = get_problems_URL(page_source, first_page)

    # Create a dictionary with the extracted data
    data = {
        'title': titles,
        'problem_URL': problems_url
    }

    # Create a DataFrame using the dictionary
    df = pd.DataFrame(data)

    # Return the DataFrame
    return df

In [41]:
def get_multiple_page_df(start=1, end=60):
    """
    Calls get_single_page_df for a range of pages and concatenates the results into a single DataFrame.

    Args:
        start (int, optional): The starting page. Default is 1.
        end (int, optional): The ending page. Default is 60.

    Returns:
        DataFrame: Pandas DataFrame containing titles, problem URLs, acceptances, and difficulties for multiple pages.
    """
    # Initialize an empty list to store DataFrames for each page
    list_of_dfs = []

    # Set the flag for the first page
    first_page = True if start == 1 else False

    # Iterate over the specified range of pages
    for i in range(start, end + 1):
        # Construct the URL for the current page
        url = 'https://leetcode.com/problemset/all/?page=' + str(i)

        # Get the DataFrame for the current page and append it to the list
        df = get_single_page_df(url, first_page)
        list_of_dfs.append(df)

        # Update the first_page flag for subsequent pages
        first_page = False

    # Concatenate the list of DataFrames into a single DataFrame
    df = pd.concat(list_of_dfs, ignore_index=True)

    # Return the final DataFrame
    return df

In [57]:
# def scrape(start=1, end=60, file_name='part1.csv'):
#     """
#     Initiates the scraping process, saving the resulting DataFrame to a CSV file.

#     Args:
#         start (int, optional): The starting page for scraping. Default is 1.
#         end (int, optional): The ending page for scraping. Default is 60.
#         file_name (str, optional): The name of the CSV file to save the scraped data. Default is 'part1.csv'.
#     """
#     # Get the DataFrame by scraping multiple pages
#     df = get_multiple_page_df(start, end)

#     # Save the DataFrame to a CSV file
#     df.to_csv(path_or_buf=file_name, index=False)

In [31]:
import json
with open('data/urls.json', 'r') as f:
    urls = json.load(f)

In [49]:
def get_is_premium(page_source):
    """
    Checks if the page indicates a premium status.

    Args:
        page_source (BeautifulSoup): The BeautifulSoup object representing the page source.

    Returns:
        str: 'True' if premium, 'False' otherwise.
    """
    # Find the element with the specified class using BeautifulSoup
    premium_element = page_source.find('div', class_='text-md mb-6 text-center text-label-2 dark:text-dark-label-2')

    # Determine premium status based on the existence of the element
    is_premium = 'True' if premium_element else 'False'

    # Return the premium status
    return is_premium

In [72]:
def get_page_source(driver, url, delay=10):
    """
    Retrieves the page source of a specified URL using Selenium and BeautifulSoup.

    Args:
        driver (webdriver): The Selenium WebDriver object.
        url (str): The URL to scrape.
        delay (int, optional): Delay in seconds to wait for the page to load. Default is 10 seconds.

    Returns:
        BeautifulSoup: The BeautifulSoup object representing the page source.
    """
    
    # Open the specified URL in the browser
    driver.get(url)

    # Allow time for the page to load (adjust delay as needed)
    time.sleep(delay)

    # Get the page source using BeautifulSoup for parsing
    page_source = BeautifulSoup(driver.page_source, 'html.parser')
    

    # Return the parsed page source
    return page_source

In [122]:
def get_title(soup):
    return soup.title.text.replace(" - LeetCode", "")

In [153]:
my_list = []

In [154]:
def scrape(df1, start=1, end=3000, file_name='x2.csv'):
    """
    Scrapes data for a range of links from the provided DataFrame and saves it to a CSV file.

    Args:
        df1 (DataFrame): The DataFrame containing problem URLs.
        start (int, optional): The starting index for scraping. Default is 1.
        end (int, optional): The ending index for scraping. Default is 3000.
        file_name (str, optional): The name of the CSV file to save the scraped data. Default is 'x2.csv'.
    """
    # Extract links for the specified range from the DataFrame
    links = df1['URL'][start - 1:end]

    # Initialize an empty list to store DataFrames for each link
    dfs = []
    
    # Set the path to the ChromeDriver executable
    #service = Service('D:/chromedriver-win64/chromedriver.exe')

    # Configure Chrome options
    options = webdriver.ChromeOptions()
    options.add_argument('--ignore-certificate-errors')  # Ignore certificate errors
    options.add_argument('--start-maximized')  # Start the browser in maximized mode
    counter = 1
    # Create a Chrome WebDriver instance with the specified service and options
    for link in links:
        i=0
        driver = webdriver.Chrome(options=options)
        try:
            page_source = get_page_source(driver, link)
        finally:
            driver.quit()

        # Create a dictionary to store scraped data
        data = {'is_premium': get_is_premium(page_source)}

        # Check if the problem is not premium before scraping additional data
        if data['is_premium'] == 'False':
            print(counter,"done")
            # Update the data dictionary with additional scraped data
            data.update({
                # try:
                #     title = get_title(page_source)
                # except Exception as e:
                #     print("get_title failed")
                #     raise
                # # try:
                # #     description = get_problem_description(page_source)
                # # except Exception as e:
                # #     print("get_problem_description failed")
                # #     raise
                # try:
                #     topic_tags = get_topic_tags(page_source)
                # except Exception as e:  
                #     print("get_topic_tags failed")
                #     raise
                # try:
                #     likes = get_likes(page_source)
                # except Exception as e:
                #     print("get_likes failed")
                #     raise   
                # try:
                #     dislikes = get_dislikes(page_source)
                # except Exception as e:
                #     print("get_dislikes failed")
                #     raise
                # try:
                #     similar_questions = get_similar_questions(page_source)
                # except Exception as e:
                #     print("get_similar_questions failed")
                #     raise
                
                'title': get_title(page_source),
                #'problem_description': get_problem_description(page_source),
                'topic_tags': get_topic_tags(page_source)
                #'accepted': get_accepted(page_source),
                #'submission': get_submission(page_source),
                #'solution': get_solution(page_source),
                #'discussion_count': get_discussion_count(page_source),
                # 'likes': get_likes(page_source),
                # 'dislikes': get_dislikes(page_source),
                # 'similar_questions': get_similar_questions(page_source)
            })
            counter += 1
            # Create a DataFrame for the current link and append it to the list
            my_list.append(data)
            df = pd.DataFrame(data, index=[i])
            dfs.append(df)
            i += 1
    #print(dfs)
    # Concatenate the list of DataFrames into a single DataFrame
    
    df = pd.concat(dfs, ignore_index=True)

    # Save the final DataFrame to a CSV file
    df.to_csv(path_or_buf=file_name, index=None)
    #print(df)

In [39]:
df_copy = pd.read_csv('data/df_copy.csv')

In [83]:
scrape(df_copy,1,df_copy.shape[0], 'data/final.csv')

0 done
0 done
0 done
0 done
0 done

KeyboardInterrupt:

In [85]:
df_copy.shape

(17641, 30)

In [88]:
new_df = df_copy[df_copy['topics'].isna()][['Title','URL']].drop_duplicates(subset=['Title'], keep='first')

In [89]:
new_df.shape

(208, 2)

In [96]:
scrape(new_df,1,new_df.shape[0], 'data/final.csv')

1 done
2 done
3 done
4 done
5 done
6 done
7 done
8 done
9 done
10 done
11 done
12 done
13 done
14 done
15 done
16 done
17 done
18 done
19 done
20 done
21 done
22 done
23 done
24 done
25 done
26 done
27 done
28 done
29 done
30 done
31 done
32 done
33 done
34 done
35 done
36 done
37 done
38 done
39 done
40 done
41 done
42 done
43 done
44 done
45 done
46 done
47 done
48 done
49 done
50 done
51 done
52 done
53 done
54 done
55 done
56 done
57 done
58 done
59 done
60 done
61 done
62 done
63 done
64 done
65 done
66 done
67 done
68 done
69 done
70 done
71 done
72 done
73 done
74 done
75 done
76 done
77 done
78 done
79 done
80 done
81 done
82 done
83 done
84 done
85 done
86 done
87 done
88 done
89 done
90 done
91 done
92 done
93 done
94 done
95 done
96 done
97 done
98 done
99 done
100 done
101 done
102 done
103 done
104 done
105 done
106 done
107 done
108 done
109 done
110 done
111 done
112 done
113 done
114 done
115 done
116 done
117 done
118 done
119 done
120 done
121 done
122 done
123 done
124 done
125 done
126 done
127 done
128 done
129 done
130 done
131 done
132 done
133 done
134 done
135 done
136 done
137 done
138 done
139 done
140 done
141 done
142 done
143 done
144 done
145 done
146 done
147 done
148 done
149 done
150 done
151 done
152 done
153 done
154 done
155 done
156 done
157 done
158 done
159 done
160 done
161 done
162 done
163 done
164 done
165 done
166 done
167 done
168 done
169 done
170 done
171 done
172 done
173 done
174 done
175 done
176 done
177 done
178 done
179 done
180 done
181 done
182 done
183 done
184 done
185 done
186 done
187 done
188 done
189 done
190 done
191 done
192 done
193 done
194 done
195 done
196 done
197 done
198 done
199 done
200 done
201 done
202 done
203 done
204 done
205 done
206 done
207 done
208 done
[  is_premium                                              title topic_tags
0      False  Minimum Number of Operations to Have Distinct ...           ,   is_premium                         title topic_tags
0      False  Rotate Non Negative Elements           ,   is_premium                       title topic_tags
0      False  Threshold Majority Queries           ,   is_premium                                      title topic_tags
0      False  Minimum Moves to Equal Array Elements III           ,   is_premium                              title topic_tags
0      False  Find Diameter Endpoints of a Tree           ,   is_premium                                         title topic_tags
0      False  Maximum Team Size with Overlapping Intervals           ,   is_premium                  title topic_tags
0      False  Swap Sex of Employees           ,   is_premium                           title topic_tags
0      False  Shortest Common Supersequence            ,   is_premium                                title topic_tags
0      False  Design an Array Statistics Tracker            ,   is_premium                      title topic_tags
0      False  Max Chunks To Make Sorted           ,   is_premium                          title topic_tags
0      False  Maximum XOR After Operations            ,   is_premium                     title topic_tags
0      False  Stock Price Fluctuation            ,   is_premium                                 title topic_tags
0      False  Maximum Sum With Exactly K Elements            ,   is_premium                           title topic_tags
0      False  Minimum Positive Sum Subarray            ,   is_premium                                title topic_tags
0      False  Maximum Height by Stacking Cuboids            ,   is_premium                                              title topic_tags
0      False  Maximize Y‑Sum by Picking a Triplet of Distinc...           ,   is_premium                                              title topic_tags
0      False  Longest Common Prefix Between Adjacent Strings...           ,   is_premium                                      title topic_tags
0      False  Minimum Number of Primes to Sum to Target           ,   is_premium                                     title topic_tags
0      False  Process String with Special Operations I           ,   is_premium                       title topic_tags
0      False  Maximum Balanced Shipments           ,   is_premium                            title topic_tags
0      False  Maximum K to Sort a Permutation           ,   is_premium                                        title topic_tags
0      False  Maximum Total from Optimal Activation Order           ,   is_premium                            title topic_tags
0      False  Minimum Time to Activate String           ,   is_premium                              title topic_tags
0      False  Minimum Stability Factor of Array           ,   is_premium            title topic_tags
0      False  Trionic Array I           ,   is_premium             title topic_tags
0      False  Trionic Array II           ,   is_premium                                         title topic_tags
0      False  Maximum Median Sum of Subsequences of Size 3           ,   is_premium                              title topic_tags
0      False  Minimum Removals to Balance Array           ,   is_premium                            title topic_tags
0      False  Balanced K-Factor Decomposition           ,   is_premium                                         title topic_tags
0      False  Minimum Operations to Equalize Binary String           ,   is_premium                 title topic_tags
0      False  Count Bowl Subarrays           ,   is_premium                          title topic_tags
0      False  Minimum Sensors to Cover Grid           ,   is_premium                 title topic_tags
0      False  Two-Letter Card Game           ,   is_premium                                              title topic_tags
0      False  Lexicographically Smallest Permutation Greater...           ,   is_premium                            title topic_tags
0      False  Sum of Perfect Square Ancestors           ,   is_premium                              title topic_tags
0      False  Maximum Calories Burnt from Jumps           ,   is_premium                                              title topic_tags
0      False  Stable Subarrays With Equal Boundary and Inter...           ,   is_premium                                    title topic_tags
0      False  Minimum Time to Complete All Deliveries           ,   is_premium                              title topic_tags
0      False  Best Time to Buy and Sell Stock V           ,   is_premium                   title topic_tags
0      False  Power Grid Maintenance           ,   is_premium                                              title topic_tags
0      False  Minimum Number of Operations to Make All Array...           ,   is_premium                                    title topic_tags
0      False  Minimum Time for K Connected Components           ,   is_premium                                              title topic_tags
0      False  Lexicographically Smallest Negated Permutation...           ,   is_premium                                              title topic_tags
0      False  Count Partitions With Max-Min Difference at Mo...           ,   is_premium                                   title topic_tags
0      False  Maximize Points After Choosing K Tasks           ,   is_premium                                              title topic_tags
0      False  Count the Number of Computer Unlocking Permuta...           ,   is_premium                            title topic_tags
0      False  Maximize Cyclic Partition Score           ,   is_premium                                           title topic_tags
0      False  Best Time to Buy and Sell Stock using Strategy           ,   is_premium                                    title topic_tags
0      False  Minimum Swaps to Avoid Forbidden Values           ,   is_premium                                         title topic_tags
0      False  Total Sum of Interaction Cost in Tree Groups           ,   is_premium                             title topic_tags
0      False  Maximum Score After Binary Swaps           ,   is_premium                  title topic_tags
0      False  Reverse String Prefix           ,   is_premium                                           title topic_tags
0      False  Maximum Bitwise AND After Increment Operations           ,   is_premium                           title topic_tags
0      False  Maximum Capacity Within Budget           ,   is_premium                                            title topic_tags
0      False  Maximum Sum of Three Numbers Divisible by Three           ,   is_premium                                  title topic_tags
0      False  Minimum Cost Path with Edge Reversals           ,   is_premium                                  title topic_tags
0      False  Minimum Cost Path with Teleportations           ,   is_premium                       title topic_tags
0      False    Count Symmetric Integers           ,   is_premium                        title topic_tags
0      False  Longest Balanced Subarray I           ,   is_premium                         title topic_tags
0      False  Longest Balanced Subarray II           ,   is_premium                         title topic_tags
0      False  Longest Balanced Substring I           ,   is_premium                          title topic_tags
0      False  Longest Balanced Substring II           ,   is_premium                                         title topic_tags
0      False  Find Maximum Value in a Constrained Sequence           ,   is_premium                                      title topic_tags
0      False  Minimum Cost to Partition a Binary String           ,   is_premium                                title topic_tags
0      False  Minimum Operations to Sort a String           ,   is_premium                                              title topic_tags
0      False  Minimum Subarray Length With Distinct Sum At L...           ,   is_premium                                           title topic_tags
0      False  Maximize Spanning Tree Stability with Upgrades           ,   is_premium                                              title topic_tags
0      False  Longest Arithmetic Sequence After Changing At ...           ,   is_premium                       title topic_tags
0      False  Sum of GCD of Formed Pairs           ,   is_premium                                             title topic_tags
0      False  Minimum Absolute Difference in Sliding Submatrix           ,   is_premium                         title topic_tags
0      False  Grid Teleportation Traversal           ,   is_premium                              title topic_tags
0      False  Maximum Walls Destroyed by Robots           ,   is_premium                                   title topic_tags
0      False  Final Element After Subarray Deletions           ,   is_premium                                     title topic_tags
0      False  XOR After Range Multiplication Queries I           ,   is_premium                                      title topic_tags
0      False  XOR After Range Multiplication Queries II           ,   is_premium                                            title topic_tags
0      False  Minimum Distance Between Three Equal Elements I           ,   is_premium                                             title topic_tags
0      False  Minimum Distance Between Three Equal Elements II           ,   is_premium                                           title topic_tags
0      False  Minimum Absolute Distance Between Mirror Pairs           ,   is_premium                                            title topic_tags
0      False  Minimum Operations to Make Array Non Decreasing           ,   is_premium                            title topic_tags
0      False  Minimum Cost to Split into Ones           ,   is_premium                                  title topic_tags
0      False  Maximize Fixed Points After Deletions           ,   is_premium         title topic_tags
0      False  Jump Game IX           ,   is_premium                                              title topic_tags
0      False  Minimum Jumps to Reach End via Prime Teleporta...           ,   is_premium                          title topic_tags
0      False  Minimum Cost to Buy Apples II           ,   is_premium                                            title topic_tags
0      False  Minimize Array Sum Using Divisible Replacements           ,   is_premium                                         title topic_tags
0      False  Minimum Flips to Make Binary String Coherent           ,   is_premium                             title topic_tags
0      False  Construct Uniform Parity Array I           ,   is_premium                              title topic_tags
0      False  Construct Uniform Parity Array II           ,   is_premium                            title topic_tags
0      False  Minimize Maximum Component Cost           ,   is_premium                    title topic_tags
0      False  Number of Perfect Pairs           ,   is_premium                             title topic_tags
0      False  Count Numbers with Unique Digits           ,   is_premium                                     title topic_tags
0      False  Employees Whose Manager Left the Company           ,   is_premium                                              title topic_tags
0      False  Find Maximum Number of Non Intersecting Substr...           ,   is_premium                                 title topic_tags
0      False  Minimum Moves to Clean the Classroom           ,   is_premium                           title topic_tags
0      False  Generate Tag for Video Caption           ,   is_premium                         title topic_tags
0      False  Remove K-Balanced Substrings           ,   is_premium                                  title topic_tags
0      False  Minimum Moves to Reach Target in Grid           ,   is_premium                   title topic_tags
0      False  Count Special Triplets           ,   is_premium                         title topic_tags
0      False  Count Number of Trapezoids I           ,   is_premium                                    title topic_tags
0      False  Minimum Moves to Balance Circular Array           ,   is_premium                             title topic_tags
0      False  Analyze Subscription Conversion            ,   is_premium                  title topic_tags
0      False  Find Missing Elements           ,   is_premium                     title topic_tags
0      False  GCD of Odd and Even Sums           ,   is_premium                         title topic_tags
0      False  Check Digitorial Permutation           ,   is_premium                          title topic_tags
0      False  Mirror Distance of an Integer           ,   is_premium                             title topic_tags
0      False  Classes With at Least 5 Students           ,   is_premium                         title topic_tags
0      False  Sort Array By Absolute Value           ,   is_premium                                              title topic_tags
0      False  Maximum Number of Subsequences After One Inser...           ,   is_premium                            title topic_tags
0      False  Find Maximum Area of a Triangle           ,   is_premium                                              title topic_tags
0      False  Count Non Decreasing Arrays With Given Digit Sums           ,   is_premium                                     title topic_tags
0      False  Most Visited Sector in  a Circular Track           ,   is_premium                                  title topic_tags
0      False  Transform Array to All Equal Elements           ,   is_premium                          title topic_tags
0      False  Find The Least Frequent Digit           ,   is_premium                     title topic_tags
0      False  Maximum Partition Factor           ,   is_premium                         title topic_tags
0      False  Better Compression of String           ,   is_premium                 title topic_tags
0      False  Design Event Manager           ,   is_premium                                              title topic_tags
0      False   Check if There Is a Valid Parentheses String ...           ,   is_premium                title topic_tags
0      False  Top Three Wineries            ,   is_premium                               title topic_tags
0      False  Minimum Swaps to Sort by Digit Sum           ,   is_premium                        title topic_tags
0      False  Maximize Subarray GCD Score           ,   is_premium                              title topic_tags
0      False  Find Weighted Median Node in Tree           ,   is_premium                                      title topic_tags
0      False  Minimum Increments to Equalize Leaf Paths           ,   is_premium                title topic_tags
0      False  Inverse Coin Change           ,   is_premium              title topic_tags
0      False  Partition String            ,   is_premium                          title topic_tags
0      False  Count Number of Trapezoids II           ,   is_premium                                          title topic_tags
0      False  Count Islands With Total Value Divisible by K           ,   is_premium                               title topic_tags
0      False  Count Prime-Gap Balanced Subarrays           ,   is_premium                                    title topic_tags
0      False  Partition Array for Maximum XOR and AND           ,   is_premium                           title topic_tags
0      False  Next Special Palindrome Number           ,   is_premium                                   title topic_tags
0      False  Partition Array Into K-Distinct Groups           ,   is_premium                          title topic_tags
0      False  Sum of Beautiful Subsequences           ,   is_premium                          title topic_tags
0      False  Number of Stable Subsequences           ,   is_premium                                   title topic_tags
0      False  Subsequence Sum After Capping Elements           ,   is_premium                      title topic_tags
0      False  Twisted Mirror Path Count           ,   is_premium                                              title topic_tags
0      False  Count Elements With Strictly Smaller and Great...           ,   is_premium                                 title topic_tags
0      False  Maximize Alternating Sum Using Swaps           ,   is_premium                                title topic_tags
0      False  Split Array With Minimum Difference           ,   is_premium                                              title topic_tags
0      False  Longest Non-Decreasing Subarray After Replacin...           ,   is_premium                                         title topic_tags
0      False  Count Distinct Integers After Removing Zeros           ,   is_premium                                         title topic_tags
0      False  Smallest Index With Digit Sum Equal to Index           ,   is_premium                                              title topic_tags
0      False  Concatenate Non-Zero Digits and Multiply by Su...           ,   is_premium                                 title topic_tags
0      False  Total Waviness of Numbers in Range I           ,   is_premium                                     title topic_tags
0      False  Largest Prime from Consecutive Prime Sum           ,   is_premium                                      title topic_tags
0      False  Process String with Special Operations II           ,   is_premium                  title topic_tags
0      False  Coupon Code Validator           ,   is_premium                                title topic_tags
0      False  Sum of Squares of Special Elements            ,   is_premium                                              title topic_tags
0      False  Maximum Profit from Trading Stocks with Discounts           ,   is_premium                   title topic_tags

In [97]:
df = pd.read_csv('data/final.csv')

In [99]:
df['topic_tags'].isnull().sum()

np.int64(208)

In [121]:
df.head(1)

   is_premium                                              title  topic_tags
0       False  Minimum Number of Operations to Have Distinct ...         NaN

In [138]:
scrape(new_df,2,2, 'data/final.csv')

1 done
['Senior', 'Array', 'Simulation', 'Weekly Contest 486']
[  is_premium                         title  \
0      False  Rotate Non Negative Elements

                                          topic_tags
0  'Senior', 'Array', 'Simulation', 'Weekly Conte...  ]
  is_premium                         title  \
0      False  Rotate Non Negative Elements

                                          topic_tags
0  'Senior', 'Array', 'Simulation', 'Weekly Conte...

In [110]:
new_df['URL'].head(1)

134    https://leetcode.com/problems/minimum-number-o...
Name: URL, dtype: str

In [112]:
new_df['URL'].head(1)

134    https://leetcode.com/problems/minimum-number-o...
Name: URL, dtype: str

In [140]:
urls[2]

'https://leetcode.com/problems/threshold-majority-queries'

In [141]:
urls[0:2]

['https://leetcode.com/problems/minimum-number-of-operations-to-have-distinct-elements',
 'https://leetcode.com/problems/rotate-non-negative-elements']

In [142]:
urls[0]

'https://leetcode.com/problems/minimum-number-of-operations-to-have-distinct-elements'

In [143]:
urls[1]

'https://leetcode.com/problems/rotate-non-negative-elements'

In [156]:
scrape(new_df,1,new_df.shape[0], 'data/final2.csv')

1 done
2 done
3 done
4 done
5 done
6 done
7 done
8 done
9 done
10 done
11 done
12 done
13 done
14 done
15 done
16 done
17 done
18 done
19 done
20 done
21 done
22 done
23 done
24 done
25 done
26 done
27 done
28 done
29 done
30 done
31 done
32 done
33 done
34 done
35 done
36 done
37 done
38 done
39 done
40 done
41 done
42 done
43 done
44 done
45 done
46 done
47 done
48 done
49 done
50 done
51 done
52 done
53 done
54 done
55 done
56 done
57 done
58 done
59 done
60 done
61 done
62 done
63 done
64 done
65 done
66 done
67 done
68 done
69 done
70 done
71 done
72 done
73 done
74 done
75 done
76 done
77 done
78 done
79 done
80 done
81 done
82 done
83 done
84 done
85 done
86 done
87 done
88 done
89 done
90 done
91 done
92 done
93 done
94 done
95 done
96 done
97 done
98 done
99 done
100 done
101 done
102 done
103 done
104 done
105 done
106 done
107 done
108 done
109 done
110 done
111 done
112 done
113 done
114 done
115 done
116 done
117 done
118 done
119 done
120 done
121 done
122 done
123 done
124 done
125 done
126 done
127 done
128 done
129 done
130 done
131 done
132 done
133 done
134 done
135 done
136 done
137 done
138 done
139 done
140 done
141 done
142 done
143 done
144 done
145 done
146 done
147 done
148 done
149 done
150 done
151 done
152 done
153 done

Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)

154 done
155 done
156 done
157 done
158 done
159 done
160 done
161 done
162 done
163 done
164 done
165 done
166 done
167 done
168 done
169 done
170 done
171 done
172 done
173 done
174 done
175 done
176 done
177 done
178 done
179 done
180 done
181 done
182 done
183 done
184 done
185 done
186 done
187 done
188 done
189 done
190 done
191 done
192 done
193 done
194 done
195 done
196 done
197 done
198 done
199 done
200 done
201 done
202 done
203 done
204 done
205 done
206 done
207 done
208 done

In [157]:
my_list

[{'is_premium': 'False',
  'title': 'Minimum Number of Operations to Have Distinct Elements',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Biweekly Contest 172'"},
 {'is_premium': 'False',
  'title': 'Rotate Non Negative Elements',
  'topic_tags': "'Senior', 'Array', 'Simulation', 'Weekly Contest 486'"},
 {'is_premium': 'False',
  'title': 'Threshold Majority Queries',
  'topic_tags': "'Senior Staff', 'Array', 'Hash Table', 'Binary Search', 'Divide and Conquer', 'Counting', 'Prefix Sum', 'Biweekly Contest 162'"},
 {'is_premium': 'False',
  'title': 'Minimum Moves to Equal Array Elements III',
  'topic_tags': "'Mid Level', 'Array', 'Math', 'Biweekly Contest 169'"},
 {'is_premium': 'False',
  'title': 'Find Diameter Endpoints of a Tree',
  'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Maximum Team Size with Overlapping Intervals',
  'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Swap Sex of Employees',
  'topic_tags': "'Database'"},
 {'is_premium': 'False',
  'title': 'Shortest Common Supersequence ',
  'topic_tags': "'Principal', 'String', 'Dynamic Programming', 'Weekly Contest 141'"},
 {'is_premium': 'False',
  'title': 'Design an Array Statistics Tracker ',
  'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Max Chunks To Make Sorted',
  'topic_tags': "'Senior', 'Array', 'Stack', 'Greedy', 'Sorting', 'Monotonic Stack', 'Weekly Contest 68'"},
 {'is_premium': 'False',
  'title': 'Maximum XOR After Operations ',
  'topic_tags': "'Staff', 'Array', 'Math', 'Bit Manipulation', 'Biweekly Contest 81'"},
 {'is_premium': 'False',
  'title': 'Stock Price Fluctuation ',
  'topic_tags': "'Staff', 'Hash Table', 'Design', 'Heap (Priority Queue)', 'Data Stream', 'Ordered Set', 'Weekly Contest 262'"},
 {'is_premium': 'False',
  'title': 'Maximum Sum With Exactly K Elements ',
  'topic_tags': "'Mid Level', 'Array', 'Greedy', 'Biweekly Contest 103'"},
 {'is_premium': 'False',
  'title': 'Minimum Positive Sum Subarray ',
  'topic_tags': "'Mid Level', 'Array', 'Sliding Window', 'Prefix Sum', 'Weekly Contest 425'"},
 {'is_premium': 'False',
  'title': 'Maximum Height by Stacking Cuboids ',
  'topic_tags': "'Senior Staff', 'Array', 'Dynamic Programming', 'Sorting', 'Weekly Contest 219'"},
 {'is_premium': 'False',
  'title': 'Maximize Y‑Sum by Picking a Triplet of Distinct X‑Values',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Greedy', 'Sorting', 'Heap (Priority Queue)', 'Biweekly Contest 158'"},
 {'is_premium': 'False',
  'title': 'Longest Common Prefix Between Adjacent Strings After Removals',
  'topic_tags': "'Senior', 'Array', 'String', 'Weekly Contest 456'"},
 {'is_premium': 'False',
  'title': 'Minimum Number of Primes to Sum to Target',
  'topic_tags': ''},
 {'is_premium': 'False', 'title': 'Just a moment...', 'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Maximum Balanced Shipments',
  'topic_tags': "'Staff', 'Array', 'Dynamic Programming', 'Stack', 'Greedy', 'Monotonic Stack', 'Weekly Contest 461'"},
 {'is_premium': 'False',
  'title': 'Maximum K to Sort a Permutation',
  'topic_tags': "'Staff', 'Array', 'Bit Manipulation', 'Weekly Contest 462'"},
 {'is_premium': 'False',
  'title': 'Maximum Total from Optimal Activation Order',
  'topic_tags': "'Staff', 'Array', 'Two Pointers', 'Greedy', 'Sorting', 'Heap (Priority Queue)', 'Weekly Contest 462'"},
 {'is_premium': 'False',
  'title': 'Minimum Time to Activate String',
  'topic_tags': "'Staff', 'Array', 'Binary Search', 'Weekly Contest 461'"},
 {'is_premium': 'False',
  'title': 'Minimum Stability Factor of Array',
  'topic_tags': "'Principal', 'Array', 'Math', 'Binary Search', 'Greedy', 'Segment Tree', 'Number Theory', 'Biweekly Contest 160'"},
 {'is_premium': 'False',
  'title': 'Trionic Array I',
  'topic_tags': "'Mid Level', 'Array', 'Weekly Contest 461'"},
 {'is_premium': 'False',
  'title': 'Trionic Array II',
  'topic_tags': "'Senior Staff', 'Array', 'Dynamic Programming', 'Weekly Contest 461'"},
 {'is_premium': 'False',
  'title': 'Maximum Median Sum of Subsequences of Size 3',
  'topic_tags': "'Senior', 'Array', 'Math', 'Greedy', 'Sorting', 'Game Theory', 'Weekly Contest 460'"},
 {'is_premium': 'False',
  'title': 'Minimum Removals to Balance Array',
  'topic_tags': "'Senior', 'Array', 'Binary Search', 'Sliding Window', 'Sorting', 'Biweekly Contest 162'"},
 {'is_premium': 'False',
  'title': 'Balanced K-Factor Decomposition',
  'topic_tags': "'Senior', 'Math', 'Backtracking', 'Number Theory', 'Weekly Contest 465'"},
 {'is_premium': 'False',
  'title': 'Minimum Operations to Equalize Binary String',
  'topic_tags': "'Senior Staff', 'Math', 'String', 'Breadth-First Search', 'Union-Find', 'Ordered Set', 'Biweekly Contest 164'"},
 {'is_premium': 'False',
  'title': 'Count Bowl Subarrays',
  'topic_tags': "'Staff', 'Array', 'Stack', 'Monotonic Stack', 'Weekly Contest 466'"},
 {'is_premium': 'False',
  'title': 'Minimum Sensors to Cover Grid',
  'topic_tags': "'Senior', 'Math', 'Biweekly Contest 163'"},
 {'is_premium': 'False',
  'title': 'Two-Letter Card Game',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'String', 'Counting', 'Enumeration', 'Biweekly Contest 164'"},
 {'is_premium': 'False',
  'title': 'Lexicographically Smallest Permutation Greater Than Target',
  'topic_tags': "'Staff', 'Hash Table', 'String', 'Greedy', 'Counting', 'Enumeration', 'Weekly Contest 472'"},
 {'is_premium': 'False',
  'title': 'Sum of Perfect Square Ancestors',
  'topic_tags': "'Senior Staff', 'Array', 'Hash Table', 'Math', 'Tree', 'Depth-First Search', 'Counting', 'Number Theory', 'Weekly Contest 471'"},
 {'is_premium': 'False',
  'title': 'Maximum Calories Burnt from Jumps',
  'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Stable Subarrays With Equal Boundary and Interior Sum',
  'topic_tags': "'Staff', 'Array', 'Hash Table', 'Prefix Sum', 'Weekly Contest 473'"},
 {'is_premium': 'False',
  'title': 'Minimum Time to Complete All Deliveries',
  'topic_tags': "'Staff', 'Math', 'Binary Search', 'Weekly Contest 474'"},
 {'is_premium': 'False',
  'title': 'Best Time to Buy and Sell Stock V',
  'topic_tags': "'Staff', 'Array', 'Dynamic Programming', 'Biweekly Contest 158'"},
 {'is_premium': 'False',
  'title': 'Power Grid Maintenance',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph Theory', 'Heap (Priority Queue)', 'Ordered Set', 'Weekly Contest 457'"},
 {'is_premium': 'False',
  'title': 'Minimum Number of Operations to Make All Array Elements Equal to 1',
  'topic_tags': "'Staff', 'Array', 'Math', 'Number Theory', 'Weekly Contest 342'"},
 {'is_premium': 'False',
  'title': 'Minimum Time for K Connected Components',
  'topic_tags': "'Staff', 'Binary Search', 'Union-Find', 'Graph Theory', 'Sorting', 'Weekly Contest 457'"},
 {'is_premium': 'False',
  'title': 'Lexicographically Smallest Negated Permutation that Sums to Target',
  'topic_tags': "'Staff', 'Array', 'Math', 'Two Pointers', 'Greedy', 'Sorting', 'Biweekly Contest 170'"},
 {'is_premium': 'False',
  'title': 'Count Partitions With Max-Min Difference at Most K',
  'topic_tags': "'Staff', 'Array', 'Dynamic Programming', 'Queue', 'Sliding Window', 'Prefix Sum', 'Monotonic Queue', 'Weekly Contest 453'"},
 {'is_premium': 'False',
  'title': 'Maximize Points After Choosing K Tasks',
  'topic_tags': "'Staff', 'Array', 'Greedy', 'Sorting', 'Heap (Priority Queue)', 'Biweekly Contest 171'"},
 {'is_premium': 'False',
  'title': 'Count the Number of Computer Unlocking Permutations',
  'topic_tags': "'Senior', 'Array', 'Math', 'Brainteaser', 'Combinatorics', 'Weekly Contest 453'"},
 {'is_premium': 'False',
  'title': 'Maximize Cyclic Partition Score',
  'topic_tags': "'Principal', 'Array', 'Dynamic Programming', 'Weekly Contest 475'"},
 {'is_premium': 'False',
  'title': 'Best Time to Buy and Sell Stock using Strategy',
  'topic_tags': "'Senior', 'Array', 'Sliding Window', 'Prefix Sum', 'Weekly Contest 463'"},
 {'is_premium': 'False',
  'title': 'Minimum Swaps to Avoid Forbidden Values',
  'topic_tags': "'Senior Staff', 'Array', 'Hash Table', 'Greedy', 'Counting', 'Weekly Contest 481'"},
 {'is_premium': 'False',
  'title': 'Total Sum of Interaction Cost in Tree Groups',
  'topic_tags': "'Senior Staff', 'Array', 'Tree', 'Depth-First Search', 'Weekly Contest 481'"},
 {'is_premium': 'False',
  'title': 'Maximum Score After Binary Swaps',
  'topic_tags': "'Staff', 'Array', 'String', 'Greedy', 'Heap (Priority Queue)', 'Biweekly Contest 172'"},
 {'is_premium': 'False',
  'title': 'Reverse String Prefix',
  'topic_tags': "'Mid Level', 'Two Pointers', 'String', 'Biweekly Contest 173'"},
 {'is_premium': 'False',
  'title': 'Maximum Bitwise AND After Increment Operations',
  'topic_tags': "'Senior Staff', 'Array', 'Greedy', 'Bit Manipulation', 'Sorting', 'Weekly Contest 484'"},
 {'is_premium': 'False',
  'title': 'Maximum Capacity Within Budget',
  'topic_tags': "'Senior', 'Array', 'Two Pointers', 'Binary Search', 'Sorting', 'Weekly Contest 485'"},
 {'is_premium': 'False',
  'title': 'Maximum Sum of Three Numbers Divisible by Three',
  'topic_tags': "'Senior', 'Array', 'Greedy', 'Sorting', 'Heap (Priority Queue)', 'Biweekly Contest 172'"},
 {'is_premium': 'False',
  'title': 'Minimum Cost Path with Edge Reversals',
  'topic_tags': "'Staff', 'Graph Theory', 'Heap (Priority Queue)', 'Shortest Path', 'Biweekly Contest 163'"},
 {'is_premium': 'False',
  'title': 'Minimum Cost Path with Teleportations',
  'topic_tags': "'Senior Staff', 'Array', 'Dynamic Programming', 'Matrix', 'Biweekly Contest 163'"},
 {'is_premium': 'False',
  'title': '  Count Symmetric Integers',
  'topic_tags': "'Mid Level', 'Math', 'Enumeration', 'Weekly Contest 361'"},
 {'is_premium': 'False',
  'title': 'Longest Balanced Subarray I',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Divide and Conquer', 'Segment Tree', 'Prefix Sum', 'Weekly Contest 472'"},
 {'is_premium': 'False',
  'title': 'Longest Balanced Subarray II',
  'topic_tags': "'Principal', 'Array', 'Hash Table', 'Divide and Conquer', 'Segment Tree', 'Prefix Sum', 'Weekly Contest 472'"},
 {'is_premium': 'False',
  'title': 'Longest Balanced Substring I',
  'topic_tags': "'Senior', 'Hash Table', 'String', 'Counting', 'Enumeration', 'Weekly Contest 471'"},
 {'is_premium': 'False',
  'title': 'Longest Balanced Substring II',
  'topic_tags': "'Staff', 'Hash Table', 'String', 'Prefix Sum', 'Weekly Contest 471'"},
 {'is_premium': 'False',
  'title': 'Find Maximum Value in a Constrained Sequence',
  'topic_tags': "'Staff', 'Array', 'Greedy', 'Biweekly Contest 173'"},
 {'is_premium': 'False',
  'title': 'Minimum Cost to Partition a Binary String',
  'topic_tags': "'Senior Staff', 'String', 'Divide and Conquer', 'Prefix Sum', 'Weekly Contest 492'"},
 {'is_premium': 'False',
  'title': 'Minimum Operations to Sort a String',
  'topic_tags': "'Staff', 'String', 'Weekly Contest 492'"},
 {'is_premium': 'False',
  'title': 'Minimum Subarray Length With Distinct Sum At Least K',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Sliding Window', 'Biweekly Contest 173'"},
 {'is_premium': 'False',
  'title': 'Maximize Spanning Tree Stability with Upgrades',
  'topic_tags': "'Senior Staff', 'Binary Search', 'Greedy', 'Union-Find', 'Graph Theory', 'Minimum Spanning Tree', 'Weekly Contest 456'"},
 {'is_premium': 'False',
  'title': 'Longest Arithmetic Sequence After Changing At Most One Element',
  'topic_tags': "'Staff', 'Array', 'Enumeration', 'Weekly Contest 493'"},
 {'is_premium': 'False',
  'title': 'Sum of GCD of Formed Pairs',
  'topic_tags': "'Senior', 'Array', 'Math', 'Two Pointers', 'Sorting', 'Simulation', 'Number Theory', 'Biweekly Contest 178'"},
 {'is_premium': 'False',
  'title': 'Minimum Absolute Difference in Sliding Submatrix',
  'topic_tags': "'Senior', 'Array', 'Sorting', 'Matrix', 'Weekly Contest 452'"},
 {'is_premium': 'False',
  'title': 'Grid Teleportation Traversal',
  'topic_tags': "'Staff', 'Array', 'Hash Table', 'Breadth-First Search', 'Matrix', 'Weekly Contest 450'"},
 {'is_premium': 'False',
  'title': 'Maximum Walls Destroyed by Robots',
  'topic_tags': "'Senior Staff', 'Array', 'Binary Search', 'Dynamic Programming', 'Sorting', 'Weekly Contest 464'"},
 {'is_premium': 'False',
  'title': 'Final Element After Subarray Deletions',
  'topic_tags': "'Staff', 'Array', 'Math', 'Brainteaser', 'Game Theory', 'Weekly Contest 487'"},
 {'is_premium': 'False',
  'title': 'XOR After Range Multiplication Queries I',
  'topic_tags': "'Senior', 'Array', 'Divide and Conquer', 'Simulation', 'Prefix Sum', 'Weekly Contest 463'"},
 {'is_premium': 'False',
  'title': 'XOR After Range Multiplication Queries II',
  'topic_tags': "'Principal', 'Array', 'Divide and Conquer', 'Prefix Sum', 'Weekly Contest 463'"},
 {'is_premium': 'False', 'title': 'Just a moment...', 'topic_tags': ''},
 {'is_premium': 'False', 'title': 'Just a moment...', 'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Minimum Absolute Distance Between Mirror Pairs',
  'topic_tags': "'Staff', 'Array', 'Hash Table', 'Math', 'Weekly Contest 478'"},
 {'is_premium': 'False',
  'title': 'Minimum Operations to Make Array Non Decreasing',
  'topic_tags': "'Staff', 'Array', 'Greedy', 'Weekly Contest 499'"},
 {'is_premium': 'False',
  'title': 'Minimum Cost to Split into Ones',
  'topic_tags': "'Senior', 'Math', 'Dynamic Programming', 'Weekly Contest 491'"},
 {'is_premium': 'False',
  'title': 'Maximize Fixed Points After Deletions',
  'topic_tags': "'Senior Staff', 'Array', 'Binary Search', 'Sorting', 'Weekly Contest 500'"},
 {'is_premium': 'False',
  'title': 'Jump Game IX',
  'topic_tags': "'Staff', 'Array', 'Dynamic Programming', 'Weekly Contest 464'"},
 {'is_premium': 'False',
  'title': 'Minimum Jumps to Reach End via Prime Teleportation',
  'topic_tags': "'Staff', 'Array', 'Hash Table', 'Math', 'Breadth-First Search', 'Number Theory', 'Weekly Contest 460'"},
 {'is_premium': 'False',
  'title': 'Minimum Cost to Buy Apples II',
  'topic_tags': "'Senior Staff', 'Array', 'Graph Theory', 'Heap (Priority Queue)', 'Shortest Path', 'Weekly Contest 501'"},
 {'is_premium': 'False',
  'title': 'Minimize Array Sum Using Divisible Replacements',
  'topic_tags': "'Staff', 'Array', 'Hash Table', 'Math', 'Greedy', 'Number Theory', 'Weekly Contest 501'"},
 {'is_premium': 'False',
  'title': 'Minimum Flips to Make Binary String Coherent',
  'topic_tags': "'Senior', 'String', 'Biweekly Contest 182'"},
 {'is_premium': 'False',
  'title': 'Construct Uniform Parity Array I',
  'topic_tags': "'Mid Level', 'Array', 'Math', 'Weekly Contest 494'"},
 {'is_premium': 'False',
  'title': 'Construct Uniform Parity Array II',
  'topic_tags': "'Senior', 'Array', 'Math', 'Weekly Contest 494'"},
 {'is_premium': 'False',
  'title': 'Minimize Maximum Component Cost',
  'topic_tags': "'Senior', 'Binary Search', 'Union-Find', 'Graph Theory', 'Sorting', 'Weekly Contest 458'"},
 {'is_premium': 'False',
  'title': 'Number of Perfect Pairs',
  'topic_tags': "'Senior', 'Array', 'Math', 'Two Pointers', 'Sorting', 'Biweekly Contest 163'"},
 {'is_premium': 'False',
  'title': 'Count Numbers with Unique Digits',
  'topic_tags': "'Math', 'Dynamic Programming', 'Backtracking'"},
 {'is_premium': 'False',
  'title': 'Employees Whose Manager Left the Company',
  'topic_tags': "'Database'"},
 {'is_premium': 'False',
  'title': 'Find Maximum Number of Non Intersecting Substrings',
  'topic_tags': "'Senior', 'Hash Table', 'String', 'Dynamic Programming', 'Greedy', 'Biweekly Contest 157'"},
 {'is_premium': 'False',
  'title': 'Minimum Moves to Clean the Classroom',
  'topic_tags': "'Staff', 'Array', 'Hash Table', 'Bit Manipulation', 'Breadth-First Search', 'Matrix', 'Weekly Contest 452'"},
 {'is_premium': 'False',
  'title': 'Generate Tag for Video Caption',
  'topic_tags': "'Mid Level', 'String', 'Simulation', 'Weekly Contest 454'"},
 {'is_premium': 'False',
  'title': 'Remove K-Balanced Substrings',
  'topic_tags': "'Staff', 'String', 'Stack', 'Simulation', 'Weekly Contest 470'"},
 {'is_premium': 'False',
  'title': 'Minimum Moves to Reach Target in Grid',
  'topic_tags': "'Senior Staff', 'Math', 'Weekly Contest 457'"},
 {'is_premium': 'False',
  'title': 'Count Special Triplets',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Counting', 'Weekly Contest 454'"},
 {'is_premium': 'False',
  'title': 'Count Number of Trapezoids I',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Math', 'Geometry', 'Weekly Contest 459'"},
 {'is_premium': 'False',
  'title': 'Minimum Moves to Balance Circular Array',
  'topic_tags': "'Staff', 'Array', 'Greedy', 'Sorting', 'Weekly Contest 480'"},
 {'is_premium': 'False',
  'title': 'Analyze Subscription Conversion ',
  'topic_tags': "'Database'"},
 {'is_premium': 'False',
  'title': 'Find Missing Elements',
  'topic_tags': "'Mid Level', 'Array', 'Hash Table', 'Sorting', 'Weekly Contest 474'"},
 {'is_premium': 'False',
  'title': 'GCD of Odd and Even Sums',
  'topic_tags': "'Mid Level', 'Math', 'Number Theory', 'Weekly Contest 464'"},
 {'is_premium': 'False',
  'title': 'Check Digitorial Permutation',
  'topic_tags': "'Senior', 'Math', 'Counting', 'Weekly Contest 490'"},
 {'is_premium': 'False',
  'title': 'Mirror Distance of an Integer',
  'topic_tags': "'Mid Level', 'Math', 'Weekly Contest 481'"},
 {'is_premium': 'False',
  'title': 'Classes With at Least 5 Students',
  'topic_tags': "'Database'"},
 {'is_premium': 'False',
  'title': 'Sort Array By Absolute Value',
  'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Maximum Number of Subsequences After One Inserting',
  'topic_tags': "'Staff', 'String', 'Dynamic Programming', 'Greedy', 'Prefix Sum', 'Weekly Contest 460'"},
 {'is_premium': 'False',
  'title': 'Find Maximum Area of a Triangle',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Math', 'Greedy', 'Geometry', 'Enumeration', 'Biweekly Contest 159'"},
 {'is_premium': 'False',
  'title': 'Count Non Decreasing Arrays With Given Digit Sums',
  'topic_tags': "'Senior Staff', 'Array', 'Dynamic Programming', 'Prefix Sum', 'Biweekly Contest 179'"},
 {'is_premium': 'False',
  'title': 'Most Visited Sector in  a Circular Track',
  'topic_tags': "'Mid Level', 'Array', 'Simulation', 'Weekly Contest 203'"},
 {'is_premium': 'False',
  'title': 'Transform Array to All Equal Elements',
  'topic_tags': "'Senior', 'Array', 'Greedy', 'Weekly Contest 453'"},
 {'is_premium': 'False',
  'title': 'Find The Least Frequent Digit',
  'topic_tags': "'Mid Level', 'Array', 'Hash Table', 'Math', 'Counting', 'Biweekly Contest 164'"},
 {'is_premium': 'False',
  'title': 'Maximum Partition Factor',
  'topic_tags': "'Senior Staff', 'Array', 'Binary Search', 'Depth-First Search', 'Breadth-First Search', 'Union-Find', 'Graph Theory', 'Biweekly Contest 167'"},
 {'is_premium': 'False',
  'title': 'Better Compression of String',
  'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Design Event Manager',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Design', 'Heap (Priority Queue)', 'Ordered Set', 'Weekly Contest 495'"},
 {'is_premium': 'False',
  'title': ' Check if There Is a Valid Parentheses String Path',
  'topic_tags': "'Senior Staff', 'Array', 'Dynamic Programming', 'Matrix', 'Weekly Contest 292'"},
 {'is_premium': 'False', 'title': 'Top Three Wineries ', 'topic_tags': ''},
 {'is_premium': 'False',
  'title': 'Minimum Swaps to Sort by Digit Sum',
  'topic_tags': "'Senior', 'Array', 'Hash Table', 'Sorting', 'Weekly Contest 450'"},
 {'is_premium': 'False',
  'title': 'Maximize Subarray GCD Score',
  'topic_tags': "'Senior Staff', 'Array', 'Math', 'Enumeration', 'Number Theory', 'Biweekly Contest 158'"},
 {'is_premium': 'False',
  'title': 'Find Weighted Median Node in Tree',
  'topic_tags': "'Principal', 'Array', 'Binary Search', 'Dynamic Programming', 'Bit Manipulation', 'Tree', 'Depth-First Search', 'Weekly Contest 454'"},
 {'is_premium': 'False',
  'title': 'Minimum Increments to Equalize Leaf Paths',

In [159]:
df_final2 = pd.read_csv('data/final2.csv')

In [161]:
df_final2.shape

(208, 3)

In [162]:
df_final2.head()

,is_premium,title,topic_tags
0,False,Minimum Number of Operations to Have Distinct ...,"'Senior', 'Array', 'Hash Table', 'Biweekly Con..."
1,False,Rotate Non Negative Elements,"'Senior', 'Array', 'Simulation', 'Weekly Conte..."
2,False,Threshold Majority Queries,"'Senior Staff', 'Array', 'Hash Table', 'Binary..."
3,False,Minimum Moves to Equal Array Elements III,"'Mid Level', 'Array', 'Math', 'Biweekly Contes..."
4,False,Find Diameter Endpoints of a Tree,NaN

In [163]:
df_final2['topic_tags'].isnull().sum()

np.int64(18)

In [166]:
df_final2[df_final2['topic_tags'].isna()]

     is_premium                                              title topic_tags
4         False                  Find Diameter Endpoints of a Tree        NaN
5         False       Maximum Team Size with Overlapping Intervals        NaN
8         False                Design an Array Statistics Tracker         NaN
17        False          Minimum Number of Primes to Sum to Target        NaN
18        False                                   Just a moment...        NaN
35        False                  Maximum Calories Burnt from Jumps        NaN
75        False                                   Just a moment...        NaN
76        False                                   Just a moment...        NaN
106       False                       Sort Array By Absolute Value        NaN
114       False                       Better Compression of String        NaN
117       False                                Top Three Wineries         NaN
168       False        Power Update After K-th Largest Insertion I        NaN
188       False                    Delayed Count of Equal Elements        NaN
191       False                     Filter Characters by Frequency        NaN
192       False                     Design Order Management System        NaN
197       False      Maximum Transactions Without Negative Balance        NaN
202       False                           Maximum Coin Collection         NaN
204       False  Maximum Distance Between Unequal Words in Array I        NaN

In [167]:
urls[4]

'https://leetcode.com/problems/find-diameter-endpoints-of-a-tree'

In [ ]:
df_final2.loc[4, 'topic_tags']= []

In [3]:
x = pd.read_csv("data/raw/final2.csv")
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   is_premium  208 non-null    bool
 1   title       208 non-null    str
 2   topic_tags  190 non-null    str
dtypes: bool(1), str(2)
memory usage: 3.6 KB

In [2]:
import pandas as pd